QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Citoyen', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sans Emploi', payment = 10 } } },
	bus = { label = 'Dashound', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	judge = { label = 'Département de la justice', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Juge', payment = 100 } } },
	lawyer = { label = 'Dynasty 8', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Avocat', payment = 50 } } },
	reporter = { label = 'Weazel’s News', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journaliste', payment = 50 } } },
	trucker = { label = 'Camionneur', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Chauffeur', payment = 50 } } },
	tow = { label = 'Camel Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Remorqueur', payment = 50 } } },
	garbage = { label = 'Household Order Bin Operations Inc.', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Éboueur', payment = 50 } } },
	vineyard = { label = 'Marlowe Vineyards', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Vigneron', payment = 50 } } },
	hotdog = { label = 'Chihuahua Hotdogs', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Cuisinier', payment = 50 } } },

	police = {
		label = 'LSPD',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Agent', payment = 75 },
			['2'] = { name = 'Sergent', payment = 100 },
			['3'] = { name = 'Lieutenant', payment = 125 },
			['4'] = { name = 'Commandant', isboss = true, payment = 150 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Paramédic', payment = 75 },
			['2'] = { name = 'Infirmier', payment = 100 },
			['3'] = { name = 'Docteur', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	realestate = {
		label = 'Dynasty 8',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Conseiller', payment = 75 },
			['2'] = { name = 'Agent', payment = 100 },
			['3'] = { name = 'Gestionnaire', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	taxi = {
		label = 'Downtown Cab.',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Chauffeur', payment = 75 },
			['2'] = { name = 'Expérimenté', payment = 100 },
			['3'] = { name = 'Superviseur', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
	cardealer = {
		label = 'Premium Deluxe Motorsport',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Vendeur', payment = 75 },
			['2'] = { name = 'Conseiller', payment = 100 },
			['3'] = { name = 'Gestionnaire', payment = 125 },
			['4'] = { name = 'Directeur', isboss = true, payment = 150 },
		},
	},
	mechanic = {
		label = 'LS Custom 1',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécanicien', payment = 75 },
			['2'] = { name = 'Expert', payment = 100 },
			['3'] = { name = 'Chef d’équipe', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
	mechanic2 = {
		label = 'LS Custom 2',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécanicien', payment = 75 },
			['2'] = { name = 'Expert', payment = 100 },
			['3'] = { name = 'Chef d’équipe', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
	mechanic3 = {
		label = 'LS Custom 3',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécanicien', payment = 75 },
			['2'] = { name = 'Expert', payment = 100 },
			['3'] = { name = 'Chef d’équipe', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
	beeker = {
		label = 'Beeker’s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécanicien', payment = 75 },
			['2'] = { name = 'Expert', payment = 100 },
			['3'] = { name = 'Chef d’équipe', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
	bennys = {
		label = 'Benny’s',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recrue', payment = 50 },
			['1'] = { name = 'Mécanicien', payment = 75 },
			['2'] = { name = 'Expert', payment = 100 },
			['3'] = { name = 'Chef d’équipe', payment = 125 },
			['4'] = { name = 'Patron', isboss = true, payment = 150 },
		},
	},
}
