QBShared = QBShared or {}
QBShared.Weapons = {
-- // WEAPONS
-- Melee
	[`weapon_unarmed`] = { name = 'weapon_unarmed', label = 'Poings', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_dagger`] = { name = 'weapon_dagger', label = 'Dague', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_bat`] = { name = 'weapon_bat', label = 'Batte', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_bottle`] = { name = 'weapon_bottle', label = 'Bouteille cassée', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_crowbar`] = { name = 'weapon_crowbar', label = 'Pied-de-biche', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_flashlight`] = { name = 'weapon_flashlight', label = 'Lampe torche', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_golfclub`] = { name = 'weapon_golfclub', label = 'Club de golf', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_hammer`] = { name = 'weapon_hammer', label = 'Marteau', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_hatchet`] = { name = 'weapon_hatchet', label = 'Hachette', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_knuckle`] = { name = 'weapon_knuckle', label = 'Poing américain', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_knife`] = { name = 'weapon_knife', label = 'Couteau', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_machete`] = { name = 'weapon_machete', label = 'Machette', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_switchblade`] = { name = 'weapon_switchblade', label = 'Couteau à cran d’arrêt', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_nightstick`] = { name = 'weapon_nightstick', label = 'Matraque', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_wrench`] = { name = 'weapon_wrench', label = 'Clé à molette', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_battleaxe`] = { name = 'weapon_battleaxe', label = 'Hache de guerre', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_poolcue`] = { name = 'weapon_poolcue', label = 'Queue de billard', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_briefcase`] = { name = 'weapon_briefcase', label = 'Valise', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_briefcase_02`] = { name = 'weapon_briefcase_02', label = 'Valise', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_garbagebag`] = { name = 'weapon_garbagebag', label = 'Sac poubelle', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_handcuffs`] = { name = 'weapon_handcuffs', label = 'Menottes', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_bread`] = { name = 'weapon_bread', label = 'Baguette', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu' },
	[`weapon_stone_hatchet`] = { name = 'weapon_stone_hatchet', label = 'Hache de pierre', weapontype = 'Melee', ammotype = nil, damagereason = 'Poignardé / Stabé / Éventré' },
	[`weapon_candycane`] = { name = 'weapon_candycane', label = 'Canne en sucre', weapontype = 'Melee', ammotype = nil, damagereason = 'Tué au corps-à-corps / Tabassé / Exécuté / Passé à tabac / Assassiné / Battu / Tué à la canne en sucre' },

	-- Handguns
	[`weapon_pistol`]                = { name = 'weapon_pistol', label = 'Pistolet', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_pistol_mk2`]            = { name = 'weapon_pistol_mk2', label = 'Pistolet Mk2', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_combatpistol`]          = { name = 'weapon_combatpistol', label = 'Pistolet de combat', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_appistol`]              = { name = 'weapon_appistol', label = 'Pistolet AP', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_stungun`]               = { name = 'weapon_stungun', label = 'Taser', weapontype = 'Pistol', ammotype = 'AMMO_STUNGUN', damagereason = 'Mort' },
	[`weapon_pistol50`]              = { name = 'weapon_pistol50', label = 'Pistolet .50 Cal', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_snspistol`]             = { name = 'weapon_snspistol', label = 'Pistolet SNS', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_snspistol_mk2`]         = { name = 'weapon_snspistol_mk2', label = 'Pistolet SNS MK2', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_heavypistol`]           = { name = 'weapon_heavypistol', label = 'Pistolet lourd', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_vintagepistol`]         = { name = 'weapon_vintagepistol', label = 'Pistolet vintage', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_flaregun`]              = { name = 'weapon_flaregun', label = 'Pistolet de détresse', weapontype = 'Pistol', ammotype = 'AMMO_FLARE', damagereason = 'Mort' },
	[`weapon_marksmanpistol`]        = { name = 'weapon_marksmanpistol', label = 'Pistolet de précision', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_revolver`]              = { name = 'weapon_revolver', label = 'Revolver', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_revolver_mk2`]          = { name = 'weapon_revolver_mk2', label = 'Revolver MK2', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_doubleaction`]          = { name = 'weapon_doubleaction', label = 'Revolver double action', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_raypistol`]             = { name = 'weapon_raypistol', label = 'Pistolet laser', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_ceramicpistol`]         = { name = 'weapon_ceramicpistol', label = 'Pistolet en céramique', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_navyrevolver`]          = { name = 'weapon_navyrevolver', label = 'Revolver naval', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_gadgetpistol`]          = { name = 'weapon_gadgetpistol', label = 'Pistolet gadget', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },
	[`weapon_stungun_mp`]            = { name = 'weapon_stungun_mp', label = 'Taser', weapontype = 'Pistol', ammotype = 'AMMO_STUNGUN', damagereason = 'Mort' },
	[`weapon_pistolxm3`]             = { name = 'weapon_pistolxm3', label = 'Pistolet XM3', weapontype = 'Pistol', ammotype = 'AMMO_PISTOL', damagereason = 'Pistolé / Explosé / Plombé / Prendre une balle' },

	-- Submachine Guns
	[`weapon_microsmg`]              = { name = 'weapon_microsmg', label = 'Micro PM', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_smg`]                   = { name = 'weapon_smg', label = 'PM', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_smg_mk2`]               = { name = 'weapon_smg_mk2', label = 'PM MK2', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_assaultsmg`]            = { name = 'weapon_assaultsmg', label = 'PM d’assaut', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_combatpdw`]             = { name = 'weapon_combatpdw', label = 'PDW de combat', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_machinepistol`]         = { name = 'weapon_machinepistol', label = 'Tec-9', weapontype = 'Submachine Gun', ammotype = 'AMMO_PISTOL', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_minismg`]               = { name = 'weapon_minismg', label = 'Mini PM', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },
	[`weapon_raycarbine`]            = { name = 'weapon_raycarbine', label = 'Carabine laser', weapontype = 'Submachine Gun', ammotype = 'AMMO_SMG', damagereason = 'Criblé / Foré / Fini / Mitraillé' },

	-- Shotguns
	[`weapon_pumpshotgun`]           = { name = 'weapon_pumpshotgun', label = 'Fusil à pompe', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_pumpshotgun_mk2`]       = { name = 'weapon_pumpshotgun_mk2', label = 'Fusil à pompe MK2', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_sawnoffshotgun`]        = { name = 'weapon_sawnoffshotgun', label = 'Fusil à canon scié', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_assaultshotgun`]        = { name = 'weapon_assaultshotgun', label = 'Fusil à pompe d’assaut', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_bullpupshotgun`]        = { name = 'weapon_bullpupshotgun', label = 'Fusil Bullpup', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_musket`]                = { name = 'weapon_musket', label = 'Mousquet', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_heavyshotgun`]          = { name = 'weapon_heavyshotgun', label = 'Fusil à pompe lourd', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_dbshotgun`]             = { name = 'weapon_dbshotgun', label = 'Fusil à double canon', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_autoshotgun`]           = { name = 'weapon_autoshotgun', label = 'Fusil automatique', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },
	[`weapon_combatshotgun`]         = { name = 'weapon_combatshotgun', label = 'Fusil de combat', weapontype = 'Shotgun', ammotype = 'AMMO_SHOTGUN', damagereason = 'Dévasté / Pulvérisé / Fusillé' },

	-- Fusils d’assaut
	[`weapon_assaultrifle`]          = { name = 'weapon_assaultrifle', label = 'Fusil d’assaut', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_assaultrifle_mk2`]      = { name = 'weapon_assaultrifle_mk2', label = 'Fusil d’assaut MK2', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_carbinerifle`]          = { name = 'weapon_carbinerifle', label = 'Carabine', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_carbinerifle_mk2`]      = { name = 'weapon_carbinerifle_mk2', label = 'Carabine MK2', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_advancedrifle`]         = { name = 'weapon_advancedrifle', label = 'Fusil avancé', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_specialcarbine`]        = { name = 'weapon_specialcarbine', label = 'Carabine spéciale', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_specialcarbine_mk2`]    = { name = 'weapon_specialcarbine_mk2', label = 'Carabine spéciale MK2', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_bullpuprifle`]          = { name = 'weapon_bullpuprifle', label = 'Fusil Bullpup', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_bullpuprifle_mk2`]      = { name = 'weapon_bullpuprifle_mk2', label = 'Fusil Bullpup MK2', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_compactrifle`]          = { name = 'weapon_compactrifle', label = 'Fusil compact', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_militaryrifle`]         = { name = 'weapon_militaryrifle', label = 'Fusil militaire', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },
	[`weapon_heavyrifle`]            = { name = 'weapon_heavyrifle', label = 'Fusil lourd', weapontype = 'Assault Rifle', ammotype = 'AMMO_RIFLE', damagereason = 'Terminé / Fusillé / Descendu / À terre' },

	-- Mitrailleuses légères
	[`weapon_mg`]                    = { name = 'weapon_mg', label = 'Mitrailleuse', weapontype = 'Light Machine Gun', ammotype = 'AMMO_MG', damagereason = 'Mitraillé / Arrosé / Ruiné' },
	[`weapon_combatmg`]              = { name = 'weapon_combatmg', label = 'Mitrailleuse de combat', weapontype = 'Light Machine Gun', ammotype = 'AMMO_MG', damagereason = 'Mitraillé / Arrosé / Ruiné' },
	[`weapon_combatmg_mk2`]          = { name = 'weapon_combatmg_mk2', label = 'Mitrailleuse de combat MK2', weapontype = 'Light Machine Gun', ammotype = 'AMMO_MG', damagereason = 'Mitraillé / Arrosé / Ruiné' },
	[`weapon_gusenberg`]             = { name = 'weapon_gusenberg', label = 'Thompson', weapontype = 'Light Machine Gun', ammotype = 'AMMO_MG', damagereason = 'Mitraillé / Arrosé / Ruiné' },

	-- Fusils de sniper
	[`weapon_sniperrifle`]           = { name = 'weapon_sniperrifle', label = 'Fusil de sniper', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER', damagereason = 'Snipé / Descendu / Visé' },
	[`weapon_heavysniper`]           = { name = 'weapon_heavysniper', label = 'Sniper lourd', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER', damagereason = 'Snipé / Descendu / Visé' },
	[`weapon_heavysniper_mk2`]       = { name = 'weapon_heavysniper_mk2', label = 'Sniper lourd MK2', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER', damagereason = 'Snipé / Descendu / Visé' },
	[`weapon_marksmanrifle`]         = { name = 'weapon_marksmanrifle', label = 'Fusil de précision', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER', damagereason = 'Snipé / Descendu / Visé' },
	[`weapon_marksmanrifle_mk2`]     = { name = 'weapon_marksmanrifle_mk2', label = 'Fusil de précision MK2', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER', damagereason = 'Snipé / Descendu / Visé' },
	[`weapon_remotesniper`]          = { name = 'weapon_remotesniper', label = 'Sniper télécommandé', weapontype = 'Sniper Rifle', ammotype = 'AMMO_SNIPER_REMOTE', damagereason = 'Snipé / Descendu / Visé' },

	-- Armes lourdes
	[`weapon_rpg`]                   = { name = 'weapon_rpg', label = 'Lance-roquettes (RPG)', weapontype = 'Heavy Weapons', ammotype = 'AMMO_RPG', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_grenadelauncher`]       = { name = 'weapon_grenadelauncher', label = 'Lance-grenades', weapontype = 'Heavy Weapons', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_grenadelauncher_smoke`] = { name = 'weapon_grenadelauncher_smoke', label = 'Lance-grenades fumigènes', weapontype = 'Heavy Weapons', ammotype = 'AMMO_GRENADELAUNCHER', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_minigun`]               = { name = 'weapon_minigun', label = 'Minigun', weapontype = 'Heavy Weapons', ammotype = 'AMMO_MINIGUN', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_firework`]              = { name = 'weapon_firework', label = 'Lance-feu d’artifice', weapontype = 'Heavy Weapons', ammotype = nil, damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_railgun`]               = { name = 'weapon_railgun', label = 'Canon électrique (Railgun)', weapontype = 'Heavy Weapons', ammotype = nil, damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_railgunxm3`]            = { name = 'weapon_railgunxm3', label = 'Canon électrique XM3', weapontype = 'Heavy Weapons', ammotype = nil, damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_hominglauncher`]        = { name = 'weapon_hominglauncher', label = 'Lance-missiles guidés', weapontype = 'Heavy Weapons', ammotype = 'AMMO_STINGER', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_compactlauncher`]       = { name = 'weapon_compactlauncher', label = 'Lance-roquettes compact', weapontype = 'Heavy Weapons', ammotype = nil, damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_rayminigun`]            = { name = 'weapon_rayminigun', label = 'Minigun laser', weapontype = 'Heavy Weapons', ammotype = 'AMMO_MINIGUN', damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_emplauncher`]           = { name = 'weapon_emplauncher', label = 'Lance-EMP', weapontype = 'Heavy Weapons', ammotype = 'AMMO_EMPLAUNCHER', damagereason = 'Mort' },

	-- Armes jetables
	[`weapon_grenade`]               = { name = 'weapon_grenade', label = 'Grenade', weapontype = 'Throwable', ammotype = nil, damagereason = 'Bombardé / Explosé / Détoné / Fait sauter' },
	[`weapon_bzgas`]                 = { name = 'weapon_bzgas', label = 'Gaz BZ', weapontype = 'Throwable', ammotype = nil, damagereason = 'Mort' },
	[`weapon_molotov`]               = { name = 'weapon_molotov', label = 'Cocktail Molotov', weapontype = 'Throwable', ammotype = nil, damagereason = 'Brûlé / Flambé / Carbonisé' },
	[`weapon_stickybomb`]            = { name = 'weapon_stickybomb', label = 'C4', weapontype = 'Throwable', ammotype = nil, damagereason = 'Bombardé / Explosé / Détoné / Fait sauter' },
	[`weapon_proxmine`]              = { name = 'weapon_proxmine', label = 'Mine de proximité', weapontype = 'Throwable', ammotype = nil, damagereason = 'Bombardé / Explosé / Détoné / Fait sauter' },
	[`weapon_snowball`]              = { name = 'weapon_snowball', label = 'Boule de neige', weapontype = 'Throwable', ammotype = nil, damagereason = 'Mort' },
	[`weapon_pipebomb`]              = { name = 'weapon_pipebomb', label = 'Bombe artisanale', weapontype = 'Throwable', ammotype = nil, damagereason = 'Bombardé / Explosé / Détoné / Fait sauter' },
	[`weapon_ball`]                  = { name = 'weapon_ball', label = 'Balle', weapontype = 'Throwable', ammotype = 'AMMO_BALL', damagereason = 'Mort' },
	[`weapon_smokegrenade`]          = { name = 'weapon_smokegrenade', label = 'Grenade fumigène', weapontype = 'Throwable', ammotype = nil, damagereason = 'Mort' },
	[`weapon_flare`]                 = { name = 'weapon_flare', label = 'Pistolet de détresse', weapontype = 'Throwable', ammotype = 'AMMO_FLARE', damagereason = 'Mort' },

	-- Divers
	[`weapon_petrolcan`]             = { name = 'weapon_petrolcan', label = 'Bidon d’essence', weapontype = 'Miscellaneous', ammotype = 'AMMO_PETROLCAN', damagereason = 'Mort' },
	[`gadget_parachute`]             = { name = 'gadget_parachute', label = 'Parachute', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_fireextinguisher`]      = { name = 'weapon_fireextinguisher', label = 'Extincteur', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_hazardcan`]             = { name = 'weapon_hazardcan', label = 'Bidon toxique', weapontype = 'Miscellaneous', ammotype = 'AMMO_PETROLCAN', damagereason = 'Mort' },
	[`weapon_fertilizercan`]         = { name = 'weapon_fertilizercan', label = 'Bidon d’engrais', weapontype = 'Miscellaneous', ammotype = 'AMMO_FERTILIZERCAN', damagereason = 'Mort' },
	[`weapon_barbed_wire`]           = { name = 'weapon_barbed_wire', label = 'Barbelés', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Transpercé' },
	[`weapon_drowning`]              = { name = 'weapon_drowning', label = 'Noyade', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_drowning_in_vehicle`]   = { name = 'weapon_drowning_in_vehicle', label = 'Noyade en véhicule', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_bleeding`]              = { name = 'weapon_bleeding', label = 'Hémorragie', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Sang épuisé' },
	[`weapon_electric_fence`]        = { name = 'weapon_electric_fence', label = 'Clôture électrique', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Electrocuté' },
	[`weapon_explosion`]             = { name = 'weapon_explosion', label = 'Explosion', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Tué / Explosé / Anéanti / Détruit / Effacé / Exterminé' },
	[`weapon_fall`]                  = { name = 'weapon_fall', label = 'Chute', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Suicide' },
	[`weapon_exhaustion`]            = { name = 'weapon_exhaustion', label = 'Épuisement', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_hit_by_water_cannon`]   = { name = 'weapon_hit_by_water_cannon', label = 'Canon à eau', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Mort' },
	[`weapon_rammed_by_car`]         = { name = 'weapon_rammed_by_car', label = 'Percuté par véhicule', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Écrasé / Renversé / Fauché' },
	[`weapon_run_over_by_car`]       = { name = 'weapon_run_over_by_car', label = 'Écrasé par véhicule', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Écrasé / Renversé / Fauché' },
	[`weapon_heli_crash`]            = { name = 'weapon_heli_crash', label = 'Crash d’hélicoptère', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Crash d’hélicoptère' },
	[`weapon_fire`]                  = { name = 'weapon_fire', label = 'Feu', weapontype = 'Miscellaneous', ammotype = nil, damagereason = 'Brûlé / Flambé / Carbonisé' },

	-- Animaux
	[`weapon_animal`]                = { name = 'weapon_animal', label = 'Animal', weapontype = 'Animals', ammotype = nil, damagereason = 'Dévoré' },
	[`weapon_cougar`]                = { name = 'weapon_cougar', label = 'Cougar', weapontype = 'Animals', ammotype = nil, damagereason = 'Dévoré' },
}
